bindl = , switch:on:Apple SMC power/lid events, exec, hype ipc call lock lock
bindl = , switch:off:Apple SMC power/lid events, exec, hyprctl dispatch dpms on
bindl = , switch:off:Apple SMC power/lid events, exec, brightnessctl --device='kbd_backlight' set 100%
