bind = SUPER ALT, SPACE, exec, $HOME/DevBox/quickshell_menu/toggle.sh
bindl = , switch:on:Apple SMC power/lid events, exec, hype ipc call lock lock
bindl = , switch:off:Apple SMC power/lid events, exec, hyprctl dispatch dpms on
bindl = , switch:off:Apple SMC power/lid events, exec, brightnessctl --device='kbd_backlight' set 100%

input {
    kb_options = altwin:swap_alt_win
    touchpad {
        natural_scroll = true
        tap-to-click = true
        clickfinger_behavior = true
    }
}

gestures {
    gesture = 3, horizontal, workspace
    gesture = 3, up, fullscreen
    gesture = 4, horizontal, workspace
}
