local var_primary = "rgb(d0bcff)"
local var_outline = "rgb(948f99)"
local var_error = "rgb(f2b8b5)"

-- Auto-generated by HypeShell - do not edit manually

-- Remove require("hype.colors") from hyprland.lua to override.
hl.config({
    general = {
        col = {
            active_border = var_primary,
            inactive_border = var_outline,
        },
    },
    group = {
        col = {
            border_active = var_primary,
            border_inactive = var_outline,
            border_locked_active = var_error,
            border_locked_inactive = var_outline,
        },
        groupbar = {
            col = {
                active = var_primary,
                inactive = var_outline,
                locked_active = var_error,
                locked_inactive = var_outline,
            },
        },
    },
})
