background = 0xFF0F1115
base = 0xFF02354E
text = 0xFFE6ECFF
alternate_base = 0xFF1A2935
bright_text = 0xFFFFFFFF
accent = 0xFF045D88
accent_secondary = 0xFF02354E
font_size = 11
small_font_size = 10
font_family = Cantarell
font_family_monospace = CaskaydiaCove Nerd Font Mono
icon_theme = Adwaita
rounding_large = 10
rounding_small = 5
