
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

# Generic preferred resolution
monitor=,preferred,auto,1

# Example for Ultrawide LG (adjust resolution as needed)
# monitor=DP-1, 3440x1440@144, 0x0, 1

# Example for Pillarboxing (Centered 16:9 on Ultrawide)
# monitor=DP-1, 1920x1080@60, 760x0, 1
