// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : internal/proto/xml/hyprland-ctm-control-v1.xml
//
// hyprland_ctm_control_v1 Protocol Copyright:
//
// Copyright © 2024 Vaxry
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package hyprland_ctm_control

import "github.com/acarlton5/HypeShell/core/pkg/go-wayland/wayland/client"

// HyprlandCtmControlManagerV1 : manager to control CTMs
//
// This object is a manager which offers requests to control CTMs.
//
// If any changes are done, once this object is destroyed, CTMs are reset back to
// an identity matrix.
type HyprlandCtmControlManagerV1 struct {
	client.BaseProxy
	blockedHandler HyprlandCtmControlManagerV1BlockedHandlerFunc
}

// NewHyprlandCtmControlManagerV1 : manager to control CTMs
//
// This object is a manager which offers requests to control CTMs.
//
// If any changes are done, once this object is destroyed, CTMs are reset back to
// an identity matrix.
func NewHyprlandCtmControlManagerV1(ctx *client.Context) *HyprlandCtmControlManagerV1 {
	hyprlandCtmControlManagerV1 := &HyprlandCtmControlManagerV1{}
	ctx.Register(hyprlandCtmControlManagerV1)
	return hyprlandCtmControlManagerV1
}

// SetCtmForOutput : set the CTM of an output
//
// Set a CTM for a wl_output.
//
// This state is not applied immediately; clients must call .commit to
// apply any pending changes.
//
// The provided values describe a 3x3 Row-Major CTM with values in the range of [0, ∞)
//
// Passing values outside of the range will raise an invalid_matrix error.
//
// The default value of the CTM is an identity matrix.
//
// If an output doesn't get a CTM set with set_ctm_for_output and commit is called,
// that output will get its CTM reset to an identity matrix.
func (i *HyprlandCtmControlManagerV1) SetCtmForOutput(output *client.Output, mat0, mat1, mat2, mat3, mat4, mat5, mat6, mat7, mat8 float64) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat0)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat1)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat2)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat3)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat4)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat5)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat6)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat7)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], mat8)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Commit : commit the pending state
//
// Commits the pending state(s) set by set_ctm_for_output.
func (i *HyprlandCtmControlManagerV1) Commit() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the manager
//
// All objects created by the manager will still remain valid, until their
// appropriate destroy request has been called.
//
// The CTMs of all outputs will be reset to an identity matrix.
func (i *HyprlandCtmControlManagerV1) Destroy() error {
	defer i.MarkZombie()
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type HyprlandCtmControlManagerV1Error uint32

// HyprlandCtmControlManagerV1Error :
const (
	// HyprlandCtmControlManagerV1ErrorInvalidMatrix : the matrix values are invalid.
	HyprlandCtmControlManagerV1ErrorInvalidMatrix HyprlandCtmControlManagerV1Error = 0
)

func (e HyprlandCtmControlManagerV1Error) Name() string {
	switch e {
	case HyprlandCtmControlManagerV1ErrorInvalidMatrix:
		return "invalid_matrix"
	default:
		return ""
	}
}

func (e HyprlandCtmControlManagerV1Error) Value() string {
	switch e {
	case HyprlandCtmControlManagerV1ErrorInvalidMatrix:
		return "0"
	default:
		return ""
	}
}

func (e HyprlandCtmControlManagerV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

// HyprlandCtmControlManagerV1BlockedEvent :
//
// This event is sent if another manager was bound by any client
// at the time the current manager was bound.
// Any set_ctm_for_output requests from a blocked manager will be
// silently ignored by the compositor.
//
// The client should destroy the manager after receiving this event.
type HyprlandCtmControlManagerV1BlockedEvent struct{}
type HyprlandCtmControlManagerV1BlockedHandlerFunc func(HyprlandCtmControlManagerV1BlockedEvent)

// SetBlockedHandler : sets handler for HyprlandCtmControlManagerV1BlockedEvent
func (i *HyprlandCtmControlManagerV1) SetBlockedHandler(f HyprlandCtmControlManagerV1BlockedHandlerFunc) {
	i.blockedHandler = f
}

func (i *HyprlandCtmControlManagerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.blockedHandler == nil {
			return
		}
		var e HyprlandCtmControlManagerV1BlockedEvent

		i.blockedHandler(e)
	}
}
