#!/usr/bin/env bash
set -euo pipefail

# === FUNCTION TO UPDATE APP-SPECIFIC THEMES ===
update_app_themes() {
  local THEME_PATH="$1"
  local MODE="$2"

  # Update Hyprland theme
  if [[ -f "$THEME_PATH/hypr.theme" ]]; then
    cp "$THEME_PATH/hypr.theme" "$HOME/.config/hypr/themes/current.theme"
  fi

  # Update Kitty theme
  if [[ -f "$THEME_PATH/kitty.theme" ]]; then
    mkdir -p "$HOME/.config/kitty"
    cp "$THEME_PATH/kitty.theme" "$HOME/.config/kitty/theme.conf"
  fi

  # Update Rofi theme
  if [[ -f "$THEME_PATH/rofi.theme" ]]; then
    mkdir -p "$HOME/.config/rofi"
    cp "$THEME_PATH/rofi.theme" "$HOME/.config/rofi/theme.rasi"
  fi

  # Update HypeShell launcher theme
  if [[ -f "$THEME_PATH/hyprlauncher.theme" ]]; then
    mkdir -p "$HOME/.config/hyprlauncher"
    cp "$THEME_PATH/hyprlauncher.theme" "$HOME/.config/hyprlauncher/style.css"
  fi

  # Update Kvantum theme
  if [[ -d "$THEME_PATH/kvantum" ]]; then
    mkdir -p "$HOME/.config/Kvantum"
    cp -r "$THEME_PATH/kvantum/"* "$HOME/.config/Kvantum/" 2>/dev/null || true
  fi
}

THEME_NAME="${1:-}"
MODE="${2:-dark}"  # light or dark mode

THEME_DIR="$HOME/.config/hype/colorschemes"
TARGET="$HOME/.config/hype/config/colors.json"

if [[ -z "$THEME_NAME" ]]; then
  echo "Usage: switch-theme.sh <theme-name | auto> [light|dark]"
  exit 1
fi

# === AUTOGENERATED THEME ===
if [[ "$THEME_NAME" == "auto" || "$THEME_NAME" == "autogen" ]]; then
  echo "Generating theme via Quickshell IPC…"

  qs -c hype-shell ipc call global regenColors

  echo "Autogenerated theme applied"
  exit 0
fi

# === STATIC THEME WITH DUAL-PALETTE SUPPORT ===
# First, try to find qml-settings.json (new unified theme format)
QML_SETTINGS="$HOME/.config/hype/themes/$THEME_NAME/qml-settings.json"
MATUGEN_CONFIG="$HOME/.config/quickshell/hype-shell/extras/matugen/config.toml"

# Tiny inline hex extractor (no jq dependency).
# Reads a top-level key (.colorsDark or .colorsLight) and inner field.
extract_palette_hex() {
  local file="$1" section="$2" field="$3"
  python3 -c "
import json, sys
with open('$file', encoding='utf-8-sig') as f:
    data = json.load(f)
print(data.get('$section', {}).get('$field', '') or '')
" 2>/dev/null
}

if [[ -f "$QML_SETTINGS" ]]; then
  echo "Loading unified theme: $THEME_NAME (mode: $MODE)"

  SECTION="colorsDark"
  [[ "$MODE" == "light" ]] && SECTION="colorsLight"

  PRIMARY_HEX="$(extract_palette_hex "$QML_SETTINGS" "$SECTION" "primary")"

  if [[ -z "$PRIMARY_HEX" ]]; then
    echo "Failed to extract $SECTION.primary from $QML_SETTINGS" >&2
    exit 1
  fi

  # Prefer matugen for full M3 palette expansion (matches existing renderer expectations).
  if command -v matugen >/dev/null 2>&1 && [[ -f "$MATUGEN_CONFIG" ]]; then
    matugen --config "$MATUGEN_CONFIG" \
      --mode "$MODE" \
      color hex "$PRIMARY_HEX" || {
        echo "matugen failed; falling back to direct palette write" >&2
        python3 -c "
import json
with open('$QML_SETTINGS', encoding='utf-8-sig') as f:
    data = json.load(f)
with open('$TARGET', 'w') as f:
    json.dump(data['$SECTION'], f, indent=2)
"
    }
  else
    # Fallback: merge the theme palette over the current colors so sparse
    # store themes can still apply without erasing the full Material palette.
    python3 -c "
import json
with open('$QML_SETTINGS', encoding='utf-8-sig') as f:
    data = json.load(f)
try:
    with open('$TARGET', encoding='utf-8-sig') as f:
        current = json.load(f)
except Exception:
    current = {}
current.update(data.get('$SECTION', {}))
with open('$TARGET', 'w') as f:
    json.dump(current, f, indent=2)
"
  fi

  # Update associated app-specific theme files (Hyprland, Kitty, etc.)
  update_app_themes "$HOME/.config/hype/themes/$THEME_NAME" "$MODE"

  echo "Theme switched to: $THEME_NAME ($MODE mode)"
  exit 0
fi

# === FALLBACK TO LEGACY COLORSCHEMES ===
SOURCE="$THEME_DIR/$THEME_NAME.json"

if [[ ! -f "$SOURCE" ]]; then
  echo "Theme not found: $THEME_NAME"
  exit 1
fi

# Atomic write
tmp="$(mktemp)"
cat "$SOURCE" > "$tmp"
mv "$tmp" "$TARGET"

echo "Theme switched to: $THEME_NAME (legacy)"
