import QtQuick
import Quickshell
import Quickshell.Io
import qs.services
import qs.modules.interface.settings

Scope {
    id: global

    // Track if notification has already been shown
    property bool themeNotificationShown: false

    // Function to show notification once
    function notifyPredefinedTheme() {
        if (!themeNotificationShown) {
            themeNotificationShown = true
            Quickshell.execDetached([
                "notify-send",
                "Hype Shell",
                `You are using a predefined theme ${Config.runtime.appearance.colors.scheme}. Color generation/Light Theme is not supported for this theme.`,
                "--urgency=normal",
                "--expire-time=5000"
            ])
        }
    }

    function applyThemeMode(requestedTheme: string) {
        const desired = String(requestedTheme || "").trim().toLowerCase()
        if (desired !== "light" && desired !== "dark")
            return

        if (Config.runtime.appearance.theme === desired)
            return

        // Predefined themes: validate variant BEFORE changing theme.
        if (!Config.runtime.appearance.colors.autogenerated) {
            const scheme = Config.runtime.appearance.colors.scheme
            const file = Theme.map[scheme]?.[desired]

            if (!file) {
                Theme.notifyMissingVariant(scheme, desired)
                return
            }

            Config.updateKey("appearance.theme", desired)

            Quickshell.execDetached([
                "bash",
                Directories.scriptsPath + "/interface/switchTheme.sh",
                file
            ])
            return
        }

        // Autogenerated themes: update mode and regenerate colors.
        Config.updateKey("appearance.theme", desired)
        genThemeColors.running = true
    }



    // Handle Global IPCs
    IpcHandler {
        target: "global"

        function toggleTheme() {
            const currentTheme = Config.runtime.appearance.theme
            const newTheme = currentTheme === "light" ? "dark" : "light"
            applyThemeMode(newTheme)
        }

        function setTheme(themeName: string) {
            applyThemeMode(themeName)
        }

        function regenColors() {
            if (Config.runtime.appearance.colors.autogenerated) {
                genThemeColors.running = true
            } else {
                notifyPredefinedTheme()
            }
        }

        function setBackgroundPath(path: string) {
            const normalized = String(path || "").trim()
            if (normalized.length === 0)
                return
            Config.updateKey("appearance.background.path", normalized)
        }

        function syncHypeBackground() {
            if (!resolveHypeBackgroundProc.running)
                resolveHypeBackgroundProc.running = true
        }

        function setHypeTheme(themeName: string) {
            let nextTheme = String(themeName || "").trim()
            if (nextTheme.length === 0)
                return
            try {
                nextTheme = decodeURIComponent(nextTheme)
            } catch (e) {
                // Keep raw value if decoding fails.
            }
            WallpaperSlideshow.setTheme(nextTheme)
        }

        function peekMediaWidget(durationMs: int) {
            const ms = durationMs > 0 ? durationMs : 5000
            Config.updateKey("plugins.mediaPlayerWidget.peekDurationMs", ms)
            Config.updateKey("plugins.mediaPlayerWidget.peekRequest", `${Date.now()}-${Math.random()}`)
        }
    }

    property var genColorsCmd: Config.runtime.appearance.colors.runMatugenUserWide
        ? [
            "bash",
            Directories.scriptsPath + "/interface/gencolors.sh",
            "--user-wide",
            Config.runtime.appearance.background.path,
            Config.runtime.appearance.colors.matugenScheme,
            Config.runtime.appearance.theme,
            Quickshell.shellPath("extras/matugen/config.toml")
        ]
        : [
            "bash",
            Directories.scriptsPath + "/interface/gencolors.sh",
            Config.runtime.appearance.background.path,
            Config.runtime.appearance.colors.matugenScheme,
            Config.runtime.appearance.theme,
            Quickshell.shellPath("extras/matugen/config.toml")
        ];

    // Process to generate colors
    Process {
        id: genThemeColors

        command: genColorsCmd
    }

    Process {
        id: resolveHypeBackgroundProc
        command: [
            "bash",
            "-lc",
            "theme=$(sed -n 's/^hypeTheme=\"\\([^\"]*\\)\"$/\\1/p' \"$HOME/.config/hype/hype.conf\" | head -n1); " +
            "wall=$(readlink -f \"$HOME/.config/hype/themes/$theme/wall.set\" 2>/dev/null || true); " +
            "if [ -n \"$wall\" ]; then enc=$(printf '%s' \"$wall\" | jq -sRr @uri | sed 's/%2F/\\//g'); printf 'file://%s' \"$enc\"; fi"
        ]

        stdout: StdioCollector {
            onStreamFinished: {
                const resolved = String(text || "").trim()
                if (resolved.length > 0) {
                    Config.updateKey("appearance.background.path", resolved)
                }
            }
        }
    }

}
