import Qt.labs.folderlistmodel
import Qt5Compat.GraphicalEffects
import QtCore
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import qs.modules.functions
import qs.services
import qs.config
import qs.modules.components

Item {
    id: wallpapersPage
    property string hypeThemeName: ""
    readonly property string themeWallpaperFolder: {
        const name = String(hypeThemeName || "").trim()
        if (name.length === 0)
            return ""
        return Quickshell.env("HOME") + "/.config/hype/themes/" + name + "/wallpapers"
    }
    readonly property string themeWallpaperFolderUrl: themeWallpaperFolder.length > 0
        ? "file://" + encodeURI(themeWallpaperFolder)
        : "file:///__hype_missing_theme_wallpapers__"

    function refreshThemeName() {
        if (!readHypeThemeProc.running)
            readHypeThemeProc.running = true
    }

    FolderListModel {
        id: wallpaperModel

        folder: wallpapersPage.themeWallpaperFolderUrl
        nameFilters: ["*.png", "*.jpg", "*.jpeg", "*.webp", "*.bmp", "*.svg"]
        showDirs: false
        showDotAndDotDot: false
    }

    Process {
        id: readHypeThemeProc
        command: [
            "bash",
            "-lc",
            "sed -n 's/^hypeTheme=\"\\([^\"]*\\)\"$/\\1/p' \"$HOME/.config/hype/hype.conf\" | head -n1"
        ]

        stdout: StdioCollector {
            onStreamFinished: {
                wallpapersPage.hypeThemeName = String(text || "").trim()
            }
        }
    }

    Timer {
        id: themeWatchTimer
        interval: 1500
        repeat: true
        running: true
        triggeredOnStart: true
        onTriggered: wallpapersPage.refreshThemeName()
    }

    // EMPTY STATE
    StyledText {
        visible: wallpaperModel.count === 0
        text: "No wallpapers found in\n" + wallpapersPage.themeWallpaperFolder
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignVCenter
        color: Appearance.m3colors.m3onSurfaceVariant
        font.pixelSize: Appearance.font.size.large
        anchors.centerIn: parent
    }

    // WALLPAPER LIST
    ListView {
        anchors.topMargin: 90
        visible: wallpaperModel.count > 0
        anchors.fill: parent
        model: wallpaperModel
        spacing: Appearance.margin.normal
        clip: true

        delegate: Item {
            width: ListView.view.width
            height: 240

            StyledRect {
                id: imgContainer

                anchors.fill: parent
                anchors.leftMargin: 20
                anchors.rightMargin: 20
                radius: Appearance.rounding.normal
                color: Appearance.m3colors.m3surfaceContainerLow
                layer.enabled: true

                Image {
                    id: wallImg

                    anchors.fill: parent
                    source: fileUrl
                    fillMode: Image.PreserveAspectCrop
                    asynchronous: true
                    cache: true
                    clip: true
                }

                StyledText {
                    anchors.centerIn: parent
                    text: "Unsupported / Corrupted Image"
                    visible: wallImg.status === Image.Error
                }

                MouseArea {
                    anchors.fill: parent
                    onClicked: {
                        Config.updateKey("appearance.background.path", fileUrl);
                        if (Config.runtime.appearance.colors.autogenerated) {
                            Quickshell.execDetached([
                                "hype", "ipc", "call", "global", "regenColors"
                            ]);
                        }                 
                }
                    cursorShape: Qt.PointingHandCursor
                }

                layer.effect: OpacityMask {

                    maskSource: Rectangle {
                        width: imgContainer.width
                        height: imgContainer.height
                        radius: imgContainer.radius
                    }

                }

            }

        }

    }

}
