import QtQuick
import Quickshell
import Quickshell.Io
import qs.services
import qs.modules.interface.settings

Scope {
    id: global

    // Track if notification has already been shown
    property bool themeNotificationShown: false

    // Function to show notification once
    function notifyPredefinedTheme() {
        if (!themeNotificationShown) {
            themeNotificationShown = true
            Quickshell.execDetached([
                "notify-send",
                "Hype Shell",
                `You are using a predefined theme ${Config.runtime.appearance.colors.scheme}. Color generation/Light Theme is not supported for this theme.`,
                "--urgency=normal",
                "--expire-time=5000"
            ])
        }
    }

    function applyThemeMode(requestedMode: string) {
        const desired = String(requestedMode || "").trim().toLowerCase()
        if (desired !== "light" && desired !== "dark")
            return

        if (Config.runtime.appearance.theme === desired)
            return

        const scheme = Config.runtime.appearance.colors.scheme
        const themeInfo = Theme.map[scheme]

        if (!themeInfo) {
            console.warn("Ipc: Theme not found in map:", scheme)
            Config.updateKey("appearance.theme", desired)
            return
        }

        if (themeInfo.type === "unified") {
            Config.updateKey("appearance.theme", desired)
            Quickshell.execDetached([
                "bash",
                Directories.scriptsPath + "/interface/switchTheme.sh",
                scheme,
                desired
            ])
        } else if (themeInfo.type === "legacy") {
            const file = themeInfo[desired]
            if (!file) {
                Theme.notifyMissingVariant(scheme, desired)
                return
            }

            Config.updateKey("appearance.theme", desired)
            Quickshell.execDetached([
                "bash",
                Directories.scriptsPath + "/interface/switchTheme.sh",
                file,
                desired
            ])
        }

        // If autogenerated, regen colors with mode
        if (Config.runtime.appearance.colors.autogenerated) {
            genThemeColors.running = true
        }
    }



    // Handle Global IPCs
    IpcHandler {
        target: "global"

        function toggleTheme() {
            const currentTheme = Config.runtime.appearance.theme
            const newTheme = currentTheme === "light" ? "dark" : "light"
            applyThemeMode(newTheme)
        }

        function setTheme(themeName: string) {
            applyThemeMode(themeName)
        }

        function regenColors() {
            if (Config.runtime.appearance.colors.autogenerated) {
                genThemeColors.running = true
            } else {
                notifyPredefinedTheme()
            }
        }

        function setBackgroundPath(path: string) {
            const normalized = String(path || "").trim()
            if (normalized.length === 0)
                return
            Config.updateKey("appearance.background.path", normalized)
        }

        function syncHypeBackground() {
            if (!resolveHypeBackgroundProc.running)
                resolveHypeBackgroundProc.running = true
        }

        function setHypeTheme(themeName: string) {
            let nextTheme = String(themeName || "").trim()
            if (nextTheme.length === 0)
                return
            try {
                nextTheme = decodeURIComponent(nextTheme)
            } catch (e) {
                // Keep raw value if decoding fails.
            }
            WallpaperSlideshow.setTheme(nextTheme)
        }

        function peekMediaWidget(durationMs: int) {
            const ms = durationMs > 0 ? durationMs : 5000
            Config.updateKey("plugins.mediaPlayerWidget.peekDurationMs", ms)
            Config.updateKey("plugins.mediaPlayerWidget.peekRequest", `${Date.now()}-${Math.random()}`)
        }
    }

    IpcHandler {
        target: "store"

        function open() {
            Globals.states.settingsOpen = false
            Globals.visiblility.sidebarLeft = false
            Globals.visiblility.sidebarRight = false
            Globals.visiblility.sidebarDev = false
            Globals.visiblility.storeOpen = true
        }

        function close() {
            Globals.visiblility.storeOpen = false
        }

        function toggle() {
            if (Globals.visiblility.storeOpen) {
                Globals.visiblility.storeOpen = false
            } else {
                open()
            }
        }
    }

    property var genColorsCmd: Config.runtime.appearance.colors.runMatugenUserWide
        ? [
            "bash",
            Directories.scriptsPath + "/interface/gencolors.sh",
            "--user-wide",
            Config.runtime.appearance.background.path,
            Config.runtime.appearance.colors.matugenScheme,
            Config.runtime.appearance.theme,
            Quickshell.shellPath("extras/matugen/config.toml")
        ]
        : [
            "bash",
            Directories.scriptsPath + "/interface/gencolors.sh",
            Config.runtime.appearance.background.path,
            Config.runtime.appearance.colors.matugenScheme,
            Config.runtime.appearance.theme,
            Quickshell.shellPath("extras/matugen/config.toml")
        ];

    // Process to generate colors
    Process {
        id: genThemeColors

        command: genColorsCmd
    }

    Process {
        id: resolveHypeBackgroundProc
        command: [
            "bash",
            "-lc",
            "theme=$(grep '^hypeTheme=' \"$HOME/.config/hype/hype.conf\" | cut -d'\"' -f2 | head -n1); " +
            "[ -n \"$theme\" ] || theme=\"Hype-Default\"; " +
            "wall=$(readlink -f \"$HOME/.config/hype/themes/$theme/wall.set\" 2>/dev/null); " +
            "if [ -z \"$wall\" ] || [ ! -f \"$wall\" ]; then " +
            "  wall=\"$HOME/.config/hype/themes/$theme/wallpapers/default.jpg\"; " +
            "fi; " +
            "if [ -z \"$wall\" ] || [ ! -f \"$wall\" ]; then " +
            "  wall=\"$HOME/.config/quickshell/hype-shell/defaults/default.jpg\"; " +
            "fi; " +
            "if [ -f \"$wall\" ]; then " +
            "  enc=$(printf '%s' \"$wall\" | jq -sRr @uri | sed 's/%2F/\\//g'); " +
            "  printf 'file://%s' \"$enc\"; " +
            "fi"
        ]

        stdout: StdioCollector {
            onStreamFinished: {
                const resolved = String(text || "").trim()
                if (resolved.length > 0) {
                    Config.updateKey("appearance.background.path", resolved)
                } else {
                    // Final fallback to absolute known default path
                    Config.updateKey("appearance.background.path", "file://" + Directories.home + "/.config/quickshell/hype-shell/defaults/default.jpg")
                }
            }
        }
    }

    Component.onCompleted: {
        resolveHypeBackgroundProc.running = true
    }

}
