import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import Appearance 1.0
import qs.modules.components
import qs.services
import qs.config

ColumnLayout {
    spacing: 24
    Layout.fillWidth: true
    Layout.margins: 32

    ColumnLayout {
        spacing: 8
        StyledText {
            text: "Wallbash"
            font.pixelSize: 28
            font.weight: Font.Bold
        }
        StyledText {
            text: "Automatically generate color schemes from your current wallpaper."
            opacity: 0.7
        }
    }

    StyledRect {
        Layout.fillWidth: true
        Layout.preferredHeight: 200
        color: Appearance.colors.colLayer1
        radius: 16
        
        RowLayout {
            anchors.fill: parent
            anchors.margins: 24
            spacing: 24

            // Wallpaper Preview
            Rectangle {
                Layout.preferredWidth: 240
                Layout.fillHeight: true
                radius: 12
                clip: true
                color: Appearance.colors.colLayer2
                
                Image {
                    anchors.fill: parent
                    source: Config.runtime.appearance.background.path
                    fillMode: Image.PreserveAspectCrop
                }
            }

            ColumnLayout {
                Layout.fillWidth: true
                spacing: 16

                StyledText {
                    text: "Current Wallpaper"
                    font.pixelSize: 18
                    font.weight: Font.Bold
                }

                RowLayout {
                    spacing: 12
                    StyledButton {
                        text: "Generate Colors"
                        icon: "auto_awesome"
                        onClicked: {
                            Wallbash.generateThemeFromWallpaper(Config.runtime.appearance.background.path, Appearance.darkMode ? "dark" : "light")
                        }
                    }
                    
                    StyledButton {
                        text: "Auto-Generate"
                        icon: Config.runtime.appearance.colors.autogenerated ? "check_circle" : "circle"
                        secondary: true
                        onClicked: {
                            Config.updateKey("appearance.colors.autogenerated", !Config.runtime.appearance.colors.autogenerated)
                        }
                    }
                }

                StyledText {
                    text: "Generated colors will be applied to the shell and supported apps."
                    font.pixelSize: 12
                    opacity: 0.5
                    Layout.fillWidth: true
                    wrapMode: Text.WordWrap
                }
            }
        }
    }

    ColumnLayout {
        spacing: 16
        Layout.fillWidth: true
        
        StyledText {
            text: "Generation Method"
            font.pixelSize: 18
            font.weight: Font.Bold
        }

        RowLayout {
            spacing: 12
            Repeater {
                model: [
                    { id: "auto", label: "Automatic", desc: "Best available" },
                    { id: "pywal", label: "Pywal", desc: "Classic extraction" },
                    { id: "native", label: "Native", desc: "Built-in QML/JS" }
                ]
                
                StyledRect {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 80
                    color: (Config.runtime.appearance.wallbashMethod || "auto") === modelData.id ? Appearance.colors.colLayer1Active : Appearance.colors.colLayer1
                    radius: 12
                    border.color: (Config.runtime.appearance.wallbashMethod || "auto") === modelData.id ? Appearance.colors.colPrimary : "transparent"
                    border.width: 1
                    
                    ColumnLayout {
                        anchors.centerIn: parent
                        spacing: 4
                        StyledText {
                            text: modelData.label
                            font.weight: Font.Bold
                            Layout.alignment: Qt.AlignHCenter
                        }
                        StyledText {
                            text: modelData.desc
                            font.pixelSize: 10
                            opacity: 0.6
                            Layout.alignment: Qt.AlignHCenter
                        }
                    }

                    MouseArea {
                        anchors.fill: parent
                        onClicked: Config.updateKey("appearance.wallbashMethod", modelData.id)
                    }
                }
            }
        }
    }

    Item { Layout.fillHeight: true }
}
