import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import Qt.labs.folderlistmodel
import Quickshell
import Quickshell.Io
import qs.config
import qs.services
import qs.modules.components

Item {
    id: root
    anchors.fill: parent

    Flickable {
        anchors.fill: parent
        contentHeight: contentLayout.implicitHeight + 100
        clip: true
        ScrollBar.vertical: ScrollBar { }

        ColumnLayout {
            id: contentLayout
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.leftMargin: Metrics.margin("normal")
            anchors.rightMargin: Metrics.margin("normal")
            anchors.topMargin: 100
            spacing: Metrics.margin("large")

            // LIGHT / DARK MODE SELECTOR
            ContentCard {
                Layout.fillWidth: true
                ColumnLayout {
                    Layout.fillWidth: true
                    spacing: Metrics.spacing(12)
                    
                    StyledText {
                        text: "Theme Mode"
                        font.pixelSize: Metrics.fontSize("large")
                        font.weight: Font.Bold
                    }

                    RowLayout {
                        Layout.fillWidth: true
                        spacing: Metrics.margin("normal")

                        StyledButton {
                            Layout.fillWidth: true
                            Layout.preferredHeight: 80
                            text: "Dark"
                            icon: "dark_mode"
                            checked: Config.runtime.appearance.theme === "dark"
                            onClicked: {
                                Quickshell.execDetached(["hype", "ipc", "call", "global", "setTheme", "dark"])
                            }
                        }

                        StyledButton {
                            Layout.fillWidth: true
                            Layout.preferredHeight: 80
                            text: "Light"
                            icon: "light_mode"
                            checked: Config.runtime.appearance.theme === "light"
                            onClicked: {
                                Quickshell.execDetached(["hype", "ipc", "call", "global", "setTheme", "light"])
                            }
                        }
                    }
                }
            }

            // WALLPAPERS SECTION
            ColumnLayout {
                Layout.fillWidth: true
                spacing: Metrics.spacing(8)
                
                StyledText {
                    text: "Wallpapers"
                    font.pixelSize: Metrics.fontSize("large")
                    font.weight: Font.Bold
                }

                // Grid of Wallpapers
                GridLayout {
                    id: wallGrid
                    columns: 2
                    columnSpacing: Metrics.margin("small")
                    rowSpacing: Metrics.margin("small")
                    Layout.fillWidth: true

                    Repeater {
                        model: wallpaperModel
                        delegate: Item {
                            Layout.fillWidth: true
                            Layout.preferredHeight: 140

                            ContentCard {
                                anchors.fill: parent
                                clip: true
                                padding: 0

                                Image {
                                    anchors.fill: parent
                                    source: fileUrl
                                    fillMode: Image.PreserveAspectCrop
                                    asynchronous: true
                                }

                                MouseArea {
                                    anchors.fill: parent
                                    onClicked: {
                                        Config.updateKey("appearance.background.path", fileUrl);
                                        if (Config.runtime.appearance.colors.autogenerated) {
                                            Quickshell.execDetached(["hype", "ipc", "call", "global", "regenColors"]);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    FolderListModel {
        id: wallpaperModel
        folder: "file://" + Quickshell.env("HOME") + "/.config/quickshell/hype-shell/defaults" // Fallback
        nameFilters: ["*.png", "*.jpg", "*.jpeg", "*.webp"]
        showDirs: false
    }

    // Try to resolve the actual theme wallpaper folder
    property string hypeThemeName: ""
    Process {
        id: readHypeThemeProc
        command: ["bash", "-lc", "sed -n 's/^hypeTheme=\"\\([^\"]*\\)\"$/\\1/p' \"$HOME/.config/hype/hype.conf\" | head -n1"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                const name = String(text || "").trim();
                if (name.length > 0) {
                    wallpaperModel.folder = "file://" + Quickshell.env("HOME") + "/.config/hype/themes/" + name + "/wallpapers"
                }
            }
        }
    }
}
